language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: make travis
notifications:
  hipchat:
    rooms:
      secure: BdAifPDzWBGeKLI9xx/ewfU7FldFVZX5a2gHBKC0Xl+k8ZJi81Y7rpJTadJXr6MjCMOj+aHuz3xryK4tYqmKduGUb0HO9h2CLnYlP/duep3K1ZSMUW1ppSBdfOunpy9OrR6HOTtNTTOiveGJ4wrq57A/hZMcgPZFLK3nY6rWois=
